version: '3'

services:
  producer-service:  # Unique service name for the device microservice
    image: producer_img
    #    ports:
    #      - "8082:8082"
    environment:
      - DB_IP=host.docker.internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.producer-ms.rule=PathPrefix(`/producer`)"
      - "traefik.http.services.producer-ms.loadbalancer.server.port=8082"
    networks:
      demo_net:
        aliases:
          - producer-service  # Explicit alias for network communication
networks:
  demo_net:
    external: true
