version: '3'

services:
  device-service:  # Unique service name for the device microservice
    image: device_img
    #    ports:
    #      - "8082:8082"
    environment:
      - DB_IP=host.docker.internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitoring-ms.rule=PathPrefix(`/device`)"
      - "traefik.http.services.monitoring-ms.loadbalancer.server.port=8081"
    networks:
      demo_net:
        aliases:
          - device-service  # Explicit alias for network communication

networks:
  demo_net:
    external: true
